POST http://localhost:3001/api/blogs
content-type: application/json

{
  "title": "Jannu's Blog",
  "author": "Jannu Peruskaveri",
  "url": "https://jannu.vaan",
  "likes": 123123123123123123123,
  "user": "5f6de2e6606bb647cece4fe1"
}